plugins {
    id 'maven-publish'
    id 'com.enonic.defaults' version '2.1.6'
    id 'com.enonic.xp.app'
}

repositories {
    mavenLocal()
    mavenCentral()
    xp.enonicRepo('dev')
}

app {
    name = 'com.enonic.uitest.contenttypes'
}

dependencies {
    compileOnly xplibs.api.core
    compileOnly xplibs.api.portal
    include xplibs.auth
    include xplibs.content
    include xplibs.context
    include xplibs.portal
    include xplibs.i18n
    include xplibs.io
    include xplibs.repo
    include xplibs.node
    include xplibs.value
    include xplibs.project
    include xplibs.export
    include libs.thymeleaf
    include 'com.enonic.lib:lib-mustache:2.1.1'
}

